// Client for the RegentMandate registry. The ABI is imported straight from
// the contract workspace (contract/abi/RegentMandate.json — regenerated by
// `forge build`, see contract/README.md). All functions are no-ops in demo
// mode (NEXT_PUBLIC_MANDATE_CONTRACT unset).

import { createPublicClient, createWalletClient, custom, http, type Abi, type Hex } from "viem"
import { baseSepolia } from "viem/chains"
import artifact from "../../../contract/abi/RegentMandate.json"
import { MANDATE_CONTRACT } from "./constants"
import type { Mandate } from "./types"

export const regentMandateAbi = artifact.abi as Abi

export function isOnChainEnabled(): boolean {
  return Boolean(MANDATE_CONTRACT)
}

const publicClient = createPublicClient({ chain: baseSepolia, transport: http() })

/** Agent address named in on-chain mandates; falls back to the owner in demo setups. */
const AGENT_ADDRESS = (process.env.NEXT_PUBLIC_AGENT_ADDRESS ?? "") as Hex

const ZERO_ADDRESS = "0x0000000000000000000000000000000000000000" as Hex

/**
 * Register the mandate boundaries on-chain so the contract — not the agent —
 * enforces budget, slippage, and expiry. Returns the transaction hash.
 */
export async function registerMandateOnChain(mandate: Mandate, owner: Hex): Promise<Hex> {
  if (!isOnChainEnabled()) throw new Error("NEXT_PUBLIC_MANDATE_CONTRACT is not set")
  if (!window.ethereum) throw new Error("No injected wallet found")

  const wallet = createWalletClient({ chain: baseSepolia, transport: custom(window.ethereum) })
  return wallet.writeContract({
    account: owner,
    address: MANDATE_CONTRACT as Hex,
    abi: regentMandateAbi,
    functionName: "createMandate",
    args: [
      AGENT_ADDRESS || owner,
      ZERO_ADDRESS, // sourceToken — resolved per-asset in production
      ZERO_ADDRESS, // targetToken
      BigInt(Math.round(mandate.budget * 1e6)),
      Math.round(mandate.maxSlippage * 100),
      BigInt(Math.floor(new Date(mandate.expiry).getTime() / 1000)),
      mandate.goal,
    ],
  })
}

export async function readRemainingBudget(onChainId: Hex): Promise<bigint> {
  if (!isOnChainEnabled()) throw new Error("NEXT_PUBLIC_MANDATE_CONTRACT is not set")
  return (await publicClient.readContract({
    address: MANDATE_CONTRACT as Hex,
    abi: regentMandateAbi,
    functionName: "remainingBudget",
    args: [onChainId],
  })) as bigint
}
